
```{r tidy data 1}
library(tidyverse)

alldata <- read_csv("qog_eureg_wide1_nov20.csv")

limited <- filter(alldata, region_name == "GERMANY")

yearsData <- select(limited, region_name, year)

filtered <- select(limited, eu_edatt_ed02_y2564f_nuts0:eu_empl_edltotal_nuts0)

filtered <- select(filtered, ends_with("nuts0"))

merged <- bind_cols(yearsData, filtered)

merged <- filter(merged, year >= 2000 & year < 2019)

colnames(merged)
```

```{r plot 1}
ggplot(data = merged) +
    geom_line(mapping = aes(x = year, y = eu_edatt_ed02_y2564f_nuts0, color = "Female")) +
    geom_line(mapping = aes(x = year, y = eu_edatt_ed02_y2564m_nuts0, color = "Male")) +
    geom_line(mapping = aes(x = year, y = eu_edatt_ed02_y2564t_nuts0, color = "Total")) +
    xlab("Year") +
    ylab("Percentage in %") +
    ggtitle("Percentage of people with lowest educational attainment, age 25-64, 2000-2018") +
    scale_color_manual(name = "Groups", values = c("Female" = "blue", "Male" = "red", "Total" = "green"))
```

```{r tidy data 2}
library(tidyverse)

alldata <- read_csv("qog_eureg_wide1_nov20.csv")

limited <- filter(alldata, year == 2015)

filtered <- select(limited, region_name, region_code, year, eu_d2jan_t_nuts0, eu_edatt_ed02_y2564f_nuts0:eu_empl_edltotal_nuts0)

onlyNuts0 <- filtered %>% select(region_name, region_code, year, ends_with("nuts0"))

final <- onlyNuts0 %>% filter_all(all_vars(!is.na(.)))

final$region_code_name <- paste(final$region_code, ":", final$region_name)
```

```{r plot 2, fig.width=12, fig.height=8}
ggplot(data = final, aes(x = region_code, y = eu_eduleave_t_nuts0, fill = region_code_name)) +
    geom_bar(stat = "identity") +
    xlab("Country") +
    ylab("Percentage in %") +
    ggtitle("Percentage of people that left education and training, age 18-24, 2015") +
    guides(fill = guide_legend(title = "Country code : Country name"))
```